## what is Numpy ?
#### NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [95]:
# Import numpy library
import numpy as np

In [38]:
# array of list list=[4, 2, 3]
list =[1,2,4,22]
np.array(list)  

array([ 1,  2,  4, 22])

In [37]:
# array 4X4 all = 0 except the main diagonal
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# 3x4 array of ones 
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# 5x5 array of zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# array([0,2,4,8,10])
np.arange(0,11,2) 

array([ 0,  2,  4,  6,  8, 10])

In [33]:
#Uniform normal distribution from(0 to 1) random array of five numbers ex: array([0.5353,0.656,0.3324,0.676,0.7856])
np.random.rand(5)

array([0.9371965 , 0.13163821, 0.12635634, 0.97062997, 0.83691939])

In [34]:
#Standard normal distribution -ve and +ve ex: array([0.452,-0.123])
np.random.randn(2)

array([-0.33985695, -0.95638734])

In [35]:
# return random numbers from low to high ex: array([54,1,21,6,8,89,65,34,2,88])
np.random.randint(1,100,10)

array([98, 48, 89, 13,  5, 55, 29, 81, 50, 97])

In [41]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 7,  7, 43,  0, 41, 47, 18,  2, 36, 36])

In [42]:
# make 2 dim array from the ranarr 5x2=10 and ranarr contain 10 values
ranarr.reshape(5,2) 

array([[ 7,  7],
       [43,  0],
       [41, 47],
       [18,  2],
       [36, 36]])

In [46]:
arr = np.random.randint(0,20,10)
arr

array([14,  3, 10, 17, 17,  1,  1,  1, 10,  9])

In [47]:
# max number of the array
arr.max() 

17

In [48]:
# min number of the array
arr.min() 

1

In [49]:
# get the location of the max number in the array for example max=49 location in array=3
arr.argmax() 

3

In [50]:
# get the location of the min number
arr.argmin() 

5

In [54]:
# shape of the array (5,5)
arr.reshape(2,5)
arr.shape

(10,)

In [56]:
# the datatype of the array
arr.dtype 

dtype('int32')

## Numpy Indexing and Selection
#### Indexing

In [57]:
arr= np.arange(0,11)
arr[8]

8

In [58]:
arr[1:5] # array([1,2,3,4])

array([1, 2, 3, 4])

In [59]:
arr[5:] # from 5 to the end of array

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5]=100 # first 5 numbers = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [66]:
slice_of_arr[:] = 99 # all array will = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [67]:
arr # the original array have changed

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy() #we copied the arr array and if we modify on arr_copy it will not affect arr indexing on 2 dim array (matrix)

In [70]:
arr_2d = np.array([[5,10,32],
                   [23,4,6],
                   [54,6,44]])
arr_2d[0][0] #//return 5

5

In [73]:
arr_2d[1,1] #return 4

4

In [72]:
arr_2d[:2,1:] #array([[10,32],[4,6]])

array([[10, 32],
       [ 4,  6]])

In [78]:
arr_2d[1:,1:] # return ([[4,6],[6,44]])

array([[ 4,  6],
       [ 6, 44]])

### Coditional selection

In [80]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
bool_arr = arr > 5 
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [82]:
arr[bool_arr] # array([6,7,8,9,10])

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<3] # array([1,2])

array([1, 2])

In [85]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2d[1:3,3:5]  #array([[13,14][23,24]])

array([[13, 14],
       [23, 24]])

### Numpy Operations
#### 1. Array with array
#### 2. Array with Scalars
#### 3. Universal array functions

In [87]:
#Array with array 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
# Array + scalar
arr + 100
arr - 100


array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [92]:
arr / arr # array([nan,1,1,1,1,1])

c:\users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [94]:
# Universal array function
np.sqrt(arr)
np.exp(arr)
np.max(arr)
np.sin(arr)
np.log(arr)

c:\users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])